### ISSUE TITLE
Non-mac shortcut key bindings

### ISSUE THREAD

**Issue by matthew-matvei** [kszcode/FuzzySearchFilesInCurrentFolder#1]
I like this plugin, but please provide Windows / Linux shortcut key bindings (or use `Ctrl+*` defaults with Mac specific overrides) :)

**Comment by kszcode** [comment]
Thank you Matthew, good point, I need to look into this.
Do you by any chance know from the top of your head how to specify the operating system?

**Comment by kszcode** [comment]
Please check the update

**Comment by matthew-matvei** [comment]
The way I achieved this locally was just to have a file named "Key Bindings (Windows).json" next to the existing file. You could add two, for Windows and Linux individually, or create one specifically for Mac (should be able to by having a filename "... (macOS)...").

I can make a pull request for this if you like

**Comment by kszcode** [comment]
Hi Matthew, please submit a pull request too, to make it cleaner.
It's also a good exercise I think.

**Comment by matthew-matvei** [comment]
Cool, will do this weekend
